### ISSUE TITLE
Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by Sketcher2010** [ist-programming/php-mvc-framework#1]
После регистрации идет отправка заголовков, однако в app.php уже вызывается echo, что запрещает дальнейшую отправку заголовков
src\site\controllers\security.controller.php:114 (header)
web\app.php:12 (echo)

**Comment by istamendil** [comment]
Мы с Вами ещё не проходили сессии и задание заголовков ответа, но забегая вперёд: рекомендуется эти дейтсвия делать как можно раньше или контролировать вывод, продумывая архитектуру всего приложения. Тут, кстати, могут помочь те самые ob-функции.
Что же касается конкретно этой ошибки, то на паре я говорил, что это строка была оставлена для технических нужд стримов. Можете убрать её, она не требуется для самого сайта или фреймворка.
